//go:build !ignore_autogenerated

/*
Copyright 2026 GEAR contributors.

Licensed for development use in the TRL 4 laboratory validation scaffold.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ability) DeepCopyInto(out *Ability) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ability.
func (in *Ability) DeepCopy() *Ability {
	if in == nil {
		return nil
	}
	out := new(Ability)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ability) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbilityList) DeepCopyInto(out *AbilityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ability, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbilityList.
func (in *AbilityList) DeepCopy() *AbilityList {
	if in == nil {
		return nil
	}
	out := new(AbilityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AbilityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbilitySpec) DeepCopyInto(out *AbilitySpec) {
	*out = *in
	out.Publisher = in.Publisher
	if in.DeclaredTriggers != nil {
		in, out := &in.DeclaredTriggers, &out.DeclaredTriggers
		*out = make([]TriggerDecl, len(*in))
		copy(*out, *in)
	}
	if in.ConnectorScopes != nil {
		in, out := &in.ConnectorScopes, &out.ConnectorScopes
		*out = make([]ConnectorScope, len(*in))
		copy(*out, *in)
	}
	if in.ActionClasses != nil {
		in, out := &in.ActionClasses, &out.ActionClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Reversibility != nil {
		in, out := &in.Reversibility, &out.Reversibility
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DataClasses != nil {
		in, out := &in.DataClasses, &out.DataClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Ceilings = in.Ceilings
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbilitySpec.
func (in *AbilitySpec) DeepCopy() *AbilitySpec {
	if in == nil {
		return nil
	}
	out := new(AbilitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AbilityStatus) DeepCopyInto(out *AbilityStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AbilityStatus.
func (in *AbilityStatus) DeepCopy() *AbilityStatus {
	if in == nil {
		return nil
	}
	out := new(AbilityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionGrant) DeepCopyInto(out *ActionGrant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionGrant.
func (in *ActionGrant) DeepCopy() *ActionGrant {
	if in == nil {
		return nil
	}
	out := new(ActionGrant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Approver) DeepCopyInto(out *Approver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Approver.
func (in *Approver) DeepCopy() *Approver {
	if in == nil {
		return nil
	}
	out := new(Approver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Caps) DeepCopyInto(out *Caps) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Caps.
func (in *Caps) DeepCopy() *Caps {
	if in == nil {
		return nil
	}
	out := new(Caps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ceilings) DeepCopyInto(out *Ceilings) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ceilings.
func (in *Ceilings) DeepCopy() *Ceilings {
	if in == nil {
		return nil
	}
	out := new(Ceilings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorScope) DeepCopyInto(out *ConnectorScope) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorScope.
func (in *ConnectorScope) DeepCopy() *ConnectorScope {
	if in == nil {
		return nil
	}
	out := new(ConnectorScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressRule) DeepCopyInto(out *EgressRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressRule.
func (in *EgressRule) DeepCopy() *EgressRule {
	if in == nil {
		return nil
	}
	out := new(EgressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationItem) DeepCopyInto(out *EscalationItem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationItem.
func (in *EscalationItem) DeepCopy() *EscalationItem {
	if in == nil {
		return nil
	}
	out := new(EscalationItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationItem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationItemList) DeepCopyInto(out *EscalationItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EscalationItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationItemList.
func (in *EscalationItemList) DeepCopy() *EscalationItemList {
	if in == nil {
		return nil
	}
	out := new(EscalationItemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EscalationItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationItemSpec) DeepCopyInto(out *EscalationItemSpec) {
	*out = *in
	out.RuleFired = in.RuleFired
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApproverSet != nil {
		in, out := &in.ApproverSet, &out.ApproverSet
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationItemSpec.
func (in *EscalationItemSpec) DeepCopy() *EscalationItemSpec {
	if in == nil {
		return nil
	}
	out := new(EscalationItemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationItemStatus) DeepCopyInto(out *EscalationItemStatus) {
	*out = *in
	in.DecidedAt.DeepCopyInto(&out.DecidedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationItemStatus.
func (in *EscalationItemStatus) DeepCopy() *EscalationItemStatus {
	if in == nil {
		return nil
	}
	out := new(EscalationItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernedAction) DeepCopyInto(out *GovernedAction) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernedAction.
func (in *GovernedAction) DeepCopy() *GovernedAction {
	if in == nil {
		return nil
	}
	out := new(GovernedAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GovernedAction) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernedActionList) DeepCopyInto(out *GovernedActionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GovernedAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernedActionList.
func (in *GovernedActionList) DeepCopy() *GovernedActionList {
	if in == nil {
		return nil
	}
	out := new(GovernedActionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GovernedActionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernedActionSpec) DeepCopyInto(out *GovernedActionSpec) {
	*out = *in
	if in.DataClasses != nil {
		in, out := &in.DataClasses, &out.DataClasses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TriggerRef = in.TriggerRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernedActionSpec.
func (in *GovernedActionSpec) DeepCopy() *GovernedActionSpec {
	if in == nil {
		return nil
	}
	out := new(GovernedActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernedActionStatus) DeepCopyInto(out *GovernedActionStatus) {
	*out = *in
	out.RuleFired = in.RuleFired
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernedActionStatus.
func (in *GovernedActionStatus) DeepCopy() *GovernedActionStatus {
	if in == nil {
		return nil
	}
	out := new(GovernedActionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mandate) DeepCopyInto(out *Mandate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mandate.
func (in *Mandate) DeepCopy() *Mandate {
	if in == nil {
		return nil
	}
	out := new(Mandate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mandate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MandateList) DeepCopyInto(out *MandateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mandate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MandateList.
func (in *MandateList) DeepCopy() *MandateList {
	if in == nil {
		return nil
	}
	out := new(MandateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MandateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MandateSpec) DeepCopyInto(out *MandateSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]Source, len(*in))
		copy(*out, *in)
	}
	if in.ConnectorGrants != nil {
		in, out := &in.ConnectorGrants, &out.ConnectorGrants
		*out = make([]ConnectorScope, len(*in))
		copy(*out, *in)
	}
	if in.ActionGrants != nil {
		in, out := &in.ActionGrants, &out.ActionGrants
		*out = make([]ActionGrant, len(*in))
		copy(*out, *in)
	}
	out.Caps = in.Caps
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Approvers != nil {
		in, out := &in.Approvers, &out.Approvers
		*out = make([]Approver, len(*in))
		copy(*out, *in)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]EgressRule, len(*in))
		copy(*out, *in)
	}
	if in.Placement != nil {
		in, out := &in.Placement, &out.Placement
		*out = new(Placement)
		(*in).DeepCopyInto(*out)
	}
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
	out.CredentialRef = in.CredentialRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MandateSpec.
func (in *MandateSpec) DeepCopy() *MandateSpec {
	if in == nil {
		return nil
	}
	out := new(MandateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MandateStatus) DeepCopyInto(out *MandateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MandateStatus.
func (in *MandateStatus) DeepCopy() *MandateStatus {
	if in == nil {
		return nil
	}
	out := new(MandateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Placement) DeepCopyInto(out *Placement) {
	*out = *in
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Placement.
func (in *Placement) DeepCopy() *Placement {
	if in == nil {
		return nil
	}
	out := new(Placement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Publisher) DeepCopyInto(out *Publisher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Publisher.
func (in *Publisher) DeepCopy() *Publisher {
	if in == nil {
		return nil
	}
	out := new(Publisher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRef) DeepCopyInto(out *RuleRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRef.
func (in *RuleRef) DeepCopy() *RuleRef {
	if in == nil {
		return nil
	}
	out := new(RuleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Source) DeepCopyInto(out *Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Source.
func (in *Source) DeepCopy() *Source {
	if in == nil {
		return nil
	}
	out := new(Source)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerDecl) DeepCopyInto(out *TriggerDecl) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerDecl.
func (in *TriggerDecl) DeepCopy() *TriggerDecl {
	if in == nil {
		return nil
	}
	out := new(TriggerDecl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerRef) DeepCopyInto(out *TriggerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerRef.
func (in *TriggerRef) DeepCopy() *TriggerRef {
	if in == nil {
		return nil
	}
	out := new(TriggerRef)
	in.DeepCopyInto(out)
	return out
}
