apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gear-fixture-store-data
  namespace: gear-system
  labels:
    app.kubernetes.io/name: gear-fixture-store
    app.kubernetes.io/part-of: gear
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
