apiVersion: apps/v1
kind: Deployment
metadata:
  name: gear-controllers
  namespace: gear-system
  labels:
    app.kubernetes.io/name: gear-controllers
    app.kubernetes.io/part-of: gear
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gear-controllers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gear-controllers
        app.kubernetes.io/part-of: gear
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: gear-controllers
          image: ghcr.io/ayond-lab/gear-controllers:dev
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
