apiVersion: v1
kind: Service
metadata:
  name: gear-policy
  namespace: gear-system
  labels:
    app.kubernetes.io/name: gear-policy
    app.kubernetes.io/part-of: gear
spec:
  selector:
    app.kubernetes.io/name: gear-policy
  ports:
    - name: http
      port: 8080
      targetPort: http
