apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gear-webhooks
  annotations:
    cert-manager.io/inject-ca-from: gear-system/gear-webhooks-serving-cert
webhooks:
  - name: pods.gear.eu
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    matchPolicy: Equivalent
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - gear-system
    objectSelector:
      matchExpressions:
        - key: gear.eu/ability
          operator: Exists
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        namespace: gear-system
        name: gear-webhooks
        path: /mutate-v1-pod
        port: 443
