apiVersion: v1
kind: Service
metadata:
  name: gear-webhooks
  namespace: gear-system
  labels:
    app.kubernetes.io/name: gear-webhooks
    app.kubernetes.io/part-of: gear
spec:
  selector:
    app.kubernetes.io/name: gear-webhooks
  ports:
    - name: webhook
      port: 443
      targetPort: webhook

